// <auto-generated />
using System;
using DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(HampadcoContext))]
    partial class HampadcoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entities.Portal.Tbl_PazirandeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Birth_Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificate_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificate_Letters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificate_NumSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificate_Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName_fa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comprehensive_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_National")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Economic_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Establishing_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family_fa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName_fa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_fa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("National_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Passport_Validity")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Set_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("arrangementcard_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("establishment_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalcard_image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalcard_image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newspaper_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passport_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("setdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statute_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workpermit_image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_PazirandeUsers");
                });

            modelBuilder.Entity("DataLayer.Entities.Tbl_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
